#!/usr/bin/env node
/*
 * serve.mjs — static server for the fictional podcast feeds.
 *
 *   node tools/capture/serve.mjs [--dir ~/oscine-capture/podcasts] [--port 8765]
 *
 * The feeds generated by make-library.mjs point at http://127.0.0.1:8765/<slug>/…,
 * so run this before subscribing in the app. Localhost only; no directory listing.
 */
import { createReadStream } from 'node:fs'
import { readFile, stat } from 'node:fs/promises'
import { createServer } from 'node:http'
import { homedir } from 'node:os'
import { extname, join, normalize, resolve } from 'node:path'

const args = process.argv.slice(2)
const opt = (name, def) => { const i = args.indexOf(name); return i === -1 ? def : args[i + 1] }
const DIR = resolve(opt('--dir', join(homedir(), 'oscine-capture', 'podcasts')))
const PORT = Number(opt('--port', 8765))
const TYPES = { '.xml': 'application/rss+xml; charset=utf-8', '.mp3': 'audio/mpeg', '.jpg': 'image/jpeg', '.json': 'application/json' }

createServer(async (req, res) => {
  const path = normalize(decodeURIComponent(new URL(req.url, 'http://x').pathname)).replace(/^(\.\.[/\\])+/, '')
  const file = join(DIR, path)
  if (!file.startsWith(DIR)) { res.writeHead(403); return res.end() }
  try {
    const s = await stat(file)
    if (!s.isFile()) { res.writeHead(404); return res.end() }
    const type = TYPES[extname(file)] || 'application/octet-stream'
    const range = req.headers.range?.match(/bytes=(\d*)-(\d*)/)
    if (range && type === 'audio/mpeg') {
      const start = range[1] ? Number(range[1]) : 0
      const end = range[2] ? Number(range[2]) : s.size - 1
      res.writeHead(206, { 'Content-Type': type, 'Content-Length': end - start + 1, 'Content-Range': `bytes ${start}-${end}/${s.size}`, 'Accept-Ranges': 'bytes' })
      return createReadStream(file, { start, end }).pipe(res)
    }
    res.writeHead(200, { 'Content-Type': type, 'Content-Length': s.size, 'Accept-Ranges': 'bytes' })
    if (req.method === 'HEAD') return res.end()
    createReadStream(file).pipe(res)
  } catch {
    res.writeHead(404); res.end()
  }
}).listen(PORT, '127.0.0.1', async () => {
  console.log(`serving ${DIR} at http://127.0.0.1:${PORT}/`)
  try {
    const m = JSON.parse(await readFile(join(DIR, '..', 'manifest.json'), 'utf8'))
    for (const p of m.podcasts) console.log(`  ${p.show}: ${p.feed}`)
  } catch { /* no manifest yet */ }
})
