<template>
  <UPage class="mx-auto max-w-6xl px-6">
    <UPageHeader title="AI/LLM Disclosure" />

    <template #right>
      <UPageAside>
        <span class="font-medium text-dimmed">Contents</span>
        <UNavigationMenu
          variant="link"
          orientation="vertical"
          highlight
          highlight-color="primary"
          :collapsible="false"
          type="single"
          :items="items"
        />
      </UPageAside>
    </template>

    <UPageBody>
      <p>
        Oscine is developed using AI tools. That being said, the application is not
        <em>vibe coded</em>, as the kids are calling it these days. Design and architectural
        decisions are not made by language models and Oscine's logo mark was not generated by AI;
        however, agentic coding tools were used to develop a script for outputting desktop icons
        derived from Oscine's logo artwork.
      </p>

      <p>
        Beyond the workflow and usage patterns described below, Oscine does not and will not employ
        language models to replace the insight and creative input of human beings. While it is
        intellectually dishonest to say "we don't use AI", it would be equally as dishonest to say
        we support AI in all its forms. Should Oscine ever seek financial sponsors for any reason,
        they will not be tech companies, especially large AI firms.
      </p>

      <p>
        The purpose of Oscine is to empower music fans to <strong>purchase and own</strong> their
        music and have a damn good way to play and enjoy it. We make no allusions about our feelings
        towards streaming behemoths and the state of the industry today. With that, the following
        sections outline the development and creative processes used to produce the Oscine
        application.
      </p>

      <p>This disclosure was not authored by a language model in any capacity.</p>

      <h2 class="text-2xl font-bold" id="software">Software Design & Engineering</h2>

      <p>
        Oscine was conceived and designed by Michael DeLally, a professional web software enginner
        with 20+ years of experience. 19 years of that experience was had entirely without the use
        of any LLM or agentic coding tools. That expertise is the first and foremost director of the
        applications development.
      </p>

      <p>
        There are three pillars that drive the architectural methodology at work in Oscine's
        development (in no particular order):
      </p>
      <ul class="list-disc list-inside">
        <li>Accessibility</li>
        <li>Performance</li>
        <li>Security</li>
      </ul>

      <p>
        No amount of cranking out tokens will put the importance on those three pillars in a means
        that instills full confidence. That day may come, but until it does, any code that is output
        or touched by an LLM is reviewed and tested first on those three pillars and then against
        the overall design sensibilities Michael has developed over the course of growing as a web
        developer.
      </p>

      <p>The majority of development work on Oscine follows this general workflow:</p>

      <h3 class="text-xl font-medium" id="design">Design & Specify</h3>
      <p>
        A large amount of what used to be the rigor of coding has been frontloaded into large
        architectual design phases that scope out features and use language models to explore
        existing code patterns to best align the new feature to the codebase's paradigms.
      </p>

      <p>
        Sometimes this includes a back and forth with a coding agent, such as Claude Code, to refine
        the language of specification documents. While initial documentation and design work is
        largely hand typed (often transcribed from scribbles in a journal), the bulk of the actual
        specification work results in documentation for models to use to implement tasks against
        features as purely as intended and possible.
      </p>

      <p>
        Michael uses an agentic coding platform he developed to help bridge the gap with these
        emerging tools and to help create an interface that helps reinforce human engagement and
        feedback loops in "agentic coding". This platform organizes architectual design
        specifications in the form of an internalized Markdown wiki that is used to distill intent
        into kanban cards. These cards follow a schema and function not too dissimilar from agile
        workflows.
      </p>

      <p>
        By providing as much human conceptualization and intent as possible, the bulk of an LLMs
        work becomes pure implementation and rote automated processes. There is no "letting it rip"
        happening here. The project and knowledge management functions keep scope aligned, and
        better yet, keep us in charge of and abreast to what these crazy things can spit out.
      </p>

      <h3 class="text-xl font-medium" id="testing">Test, Refine, & Debug</h3>
      <p>
        In large part, this has been and always will be the most involved aspect of software
        engineering of <em>any</em> kind. Coding models both help and hurt with this process. Given
        that, AI coding tools are predominantly only used to generate and run unit and functional
        tests against business logic. UI and UX testing is largely done old school manual, but
        Oscine does feature visual validation scripts that were developed with the assitance of
        coding models.
      </p>

      <p>
        When bugs occur or something is obviously broken or hallucinated slop, it is the tried and
        true debugging techniques gathered over years of software development that get used here. If
        a coding agent is to be used to address issues, it is never a "fix this". Instead, a clear
        description of the issue, using as much technical reference and instruction as possible is
        given. More often than not, however, this back and forth with agents does not occur because
        the initial design phases of an implementation were well fleshed out.
      </p>

      <p>
        Most of Oscine's visuals are left up to our component library Nuxt UI. So, in 90% of the
        cases, an agent with access to Nuxt UI's MCP server will stick to the script for scaffolding
        out basic layouts. However, the overwhelming majority of the visual design refinement
        happens with (God this sounds weird to say) hand coding and tweaking of values.
      </p>

      <h3 class="text-xl font-medium" id="ci">Deployment, CI, & Issue Triage</h3>
      <p>
        Oscine is deployed through pre-existing CI automation workflows that do not leverage AI
        agents or tools. That said, these flows may be kicked off fully, or in part, by a language
        model and most pull request messages are generated at the time of deployment by an LLM. They
        are reviewed for glaring errors and fabrications, and are amended in such cases.
      </p>

      <p>
        We take issue collection very seriously and do not leave it up to language models or "code
        review" agents to triage or prioritize the addressing of bug fixes, security issues, or
        general usage concerns. Unless the scale of issue accrual rapidly outpaces the ability to
        address them, Oscine will not rely on these tools in the future. Given this, however, the
        actual implementation work towards resolving an issue will adhere to the workflows outlined
        in this disclosure.
      </p>

      <h2 class="text-2xl font-bold" id="visuals">Visual Design Outside of the Software Scope</h2>
      <p>
        As briefly explained above, Oscine does not and will never support the generation of
        artistic media by language/diffusion models. Any visual element you see that is not purely
        driven by code is crafted through any number of traditional and digital art practices.
      </p>

      <p>
        The Oscine <Mark size="size-5" dimmed /> logomark was hand drawn, scanned, and digitally
        refined using the vector art tool, Inkscape. All fonts and icons are used with express
        consent from their licenses and are freely available. As stated in the preamble, the Oscine
        desktop icon images are generated by a build script that styles and resizes the vector logo
        at build time to ship alongside the final application executables. This script was largely
        output by a language model to automate the process, which would have normally been something
        you'd do in some capacity, either within your graphics editing program or via script.
      </p>

      <p>
        All photography featured in Oscine via network provided data or otherwise is provided with
        proper attributions. Given the nature of how these images are collected, we cannot make a
        guarantee that no image will be AI generated. Your best bet for avoiding that would be to
        not download AI music or listen to artists who feel the need to generate art or photos for
        their works.
      </p>

      <h2 class="text-2xl font-bold" id="writing">Technical Writing & Language Application</h2>
      <p>
        During the course of scaffolding and preparing layouts, coding agents will (even when asked
        not to, sometimes) invariably place textual information in the application. All final copy
        direction goes through a human filter and in all frankness, most copy will be at the very
        least shortened by an LLM or outright rewritten by Michael.
      </p>

      <p>
        These language models can definitely be useful for fast and concise technical documentation,
        but they are actually really shitty at very fine descriptive text that doesn't devolve into
        a word soup of prose. Given this reality, agent written language in Oscine is heavily
        scrutinized.
      </p>

      <h2 class="text-2xl font-bold" id="statement">Developer's Statement</h2>
      <p class="italic">
        This section is purely the opinion of Michael DeLally. While it certainly represents Oscine,
        it should not be confused with how Oscine should position itself in order to be a successful
        piece of software. The issues inherent to language models and their use are myriad, complex,
        and worthy of any and all discussion. This statement is not intended to shield Michael from
        blame or to protect him against the claims made above. The preceeding disclosure and this
        statement are not legally binding documents, just an elaboration of a social contract.
      </p>

      <p>
        Honestly, if you've read this far (or even skipped to this part), kudos to you. I felt the
        need to draft this disclosure due to the ever increasingly difficult conversations
        surrounding artificial intelligence. It is likely to evolve, as do my feelings and
        frustrations with this technology and its impact on not only my livelihood and wellbeing,
        but our political and ecological environments.
      </p>

      <p>
        The effects of massive AI datacenter operations on the planet and local ecology cannot be
        ignored. Governments are not doing enough to ensure this technology comes about in an
        environmentally friendly way, whatsoever. Energy consumption taxes are a step in the right
        direction, but punitive and regulatory legislation must be a priority, too. Big tech must be
        held accountable for how this has taken place and should be heavily regulated moving
        forward.
      </p>

      <p>
        This technology, for some, if not most, is not going anywhere. The forces behind it are
        monolithic and are led by imperfect, greedy egomaniacs with a psychotic penchant to prove
        themselves to somebody, for some reason. That doesn't mean to just rollover and accept it as
        fate. That doesn't also mean, however, that we should seek to disarm ourselves of a
        knowledge and power that the political and financial elite will asuredly use as a cudgel
        (they already are, between private sector surveilance and military intelligence operations).
      </p>

      <p>
        I am a firm believer in willpower. I don't delude myself into thinking we can
        <em class="font-bold">just</em>
        will ourselves into any reality or to overcome struggles that have been oppressed upon us,
        but I feel we owe it to ourselves to become a bigger part of this conversation instead of
        just an angry voice. If that conversation leads to a drastic or even total reduction of
        consumer or open sourced/weighted models, then the next conversation becomes how do we
        combat their use by the forces of private capital and violent executive governments?
      </p>

      <p>
        Consequently, I believe, if we have the willpower to see this to an end that is destructive,
        then by all means, it will be. On the inverse, if we can see ourselves to an end where this
        technology is liberated from carcinogenic corporations and steered by democratic ideals and
        environmental stability (as should all industry, in my mind), it is hard to argue that it
        cannot serve a greater good than it currently feigns to.
      </p>

      <p>
        For my purposes, I initially bucked coding models with all the vitriol I had. I feared the
        creative process and critical thinking would be robbed from me - and then what would I have
        left? I don't know if the same can be said for younger, more maleable minds, but with
        intention (and the ever pressing anxiety) to keep the qualities of my craft that I truly
        enjoy intact, I moved on from existential dread to finding a way to make it work for me.
      </p>

      <p>
        Mostly, this was due the increasing pressures in my career. While I am fortunate to work for
        a company who has not adopted AI mandates or crammed it down our throats (when in fact has
        been measured, careful, and budgetary with it), being on one of the more cutting edge
        internal dev teams in the organization came with a certain call to arms in seeing just what
        adoption of these tools could look like.
      </p>

      <p>
        By owning the direction of our team's use of coding agents and not being dictated or
        deferring to suits, we got to decide our limits and workflows. There is a little friction
        and our codebases are growing very fast - but for now, it seems that the velocity has been
        met with a continued desire to learn, communicate, and instill best practices. We are after
        all - software engineers and the accountability ultimately lies on us.
      </p>

      <p>
        The seeming practical necessity of these tools in my professional work didn't fully bleed
        into my work as a hobby software and game developer. It wasn't until I decided to work on my
        coding tool, Kleron, that I started to see where I could find enjoyment in this new process.
      </p>

      <p>
        What I didn't forsee, and what initially didn't happen, was how much more fluent of a
        developer it has made me. I'll explain what I mean by that, shortly; but, it must be noted
        that I am diagnosed with ADHD and for the overwhelming majority of my life, and most
        especially my adult life, have struggled with executive function, time management, and
        wavering bouts of inattentiveness and hyperfocus. It is a medical cliche that people who
        suffer from ADHD are often less intelligent (or that good grades are a sign that they can't
        have it) and just grow out of it.
      </p>

      <p>
        My experience in life was almost the opposite. I had no patience for normal classroom
        proceedings, regiment, and rigamarole. I wasn't struggling to grasp the material, I was
        frustrated that there wasn't more. My brain can handle the flow of information - but it
        stumbles over the arbitrary means for which it can be expressed.
      </p>

      <p>
        So, when I say that these tools have made me a more <em>fluent</em> developer, I mean that
        is has allowed me to more eloquently and effectively "speak" my ideas into existence. And of
        course, one could say, "Well duh! You're having a thing do things for you." While there is
        certainly truth to that claim, I cannot stress enough how important the will and intention
        to keep the quality of the craft alive (a deeply personal thing, I have come to find) makes
        the difference.
      </p>

      <p>
        I didn't come into this blindly. I have been coding websites and web-driven software since I
        was 11 years old (as of this writing I am 34). In the 20 some odd years I've been doing
        this, the act of typing syntax into a keyboard has never been the part that I enjoy. It has
        been a sticking point because I will bounce between files or completely lose my train of
        thought mid edit. I was never incapable of coming up with and developing good websites and
        software. I could just not do it fast enough before I was distracted, disinterested, or
        over-ambitioned myself into oblivion.
      </p>

      <p>
        For what it's worth - should I be able to? It's a question I wrest with almost every time I
        sit down to work on an app or game. The important fact I try keep foremost in my mind:
        <strong>you must own your craft, your identity, and apply your experiences</strong>. I do
        not have these language models fanticize ideas for me. I do not have them make overarching
        archtitectural decisions or allow them to pick languages, libraries, frameworks, or patterns
        I am not at least familiar with, but almost always have used or leveraged professionally
        prior to this paradigm shift.
      </p>

      <p>
        My policy for involving AI in the actual finished Oscine application is fairly reserved. I
        do not have any plans to make Oscine an "AI-driven" or "AI-assisted" application. The extent
        to which Oscine could interface with an LLM would a opt-in only, MCP server that could be
        used with an agent to access your library, make playlists, or clean up tags. Oscine will
        never have some cute little anamorophic chatbot trying to manipulate you into listening to
        Taylor Swift - I can promise that!
      </p>

      <p>I often mark my projects in some place or another with:</p>

      <p class="font-bold text-xl">Created/Made/Built with ❤️ by Michael DeLally</p>

      <p>
        And that is because it is true. Above all else, I truly enjoy the craft of making software
        that I can enjoy and I hope that the ones I do share with the world can be enjoyed, too!
        Thanks for reading this in any capacity - if you have any questions, comments, or concerns
        about this disclosure and use of AI with the Oscine music player, please reach out via
        GitHub Issues.
      </p>

      <p>- Michael DeLally, <em>founder and core maintainer</em></p>
    </UPageBody>
  </UPage>
</template>

<script lang="ts" setup>
const items: NavigationMenuItem[] = [
  {
    label: "Software Design",
    to: "#software",
    defaultOpen: true,
    children: [
      { label: "Design & Specify", to: "#design" },
      { label: "Testing", to: "#testing" },
      { label: "Deployment", to: "#ci" },
    ],
  },
  {
    label: "Visual Design",
    to: "#visuals",
    defaultOpen: true,
  },
  {
    label: "Technical Writing",
    to: "#writing",
    defaultOpen: true,
  },
  {
    label: "Dev Statement",
    to: "#statement",
    defaultOpen: true,
  },
];
</script>
